### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by ONourry** [matsuoharuki/pbl2_group2#7]
[Value: High]

[Risk: High]

Tasks

- [x] Setup Database Issue ref: #1 
- [x] Install Framework Issue ref: #1 
- [x] Setup environment Issue ref: #1 
- [x] Setup logging Issue ref: #1 

Selected Technologies:

Front-end: Vue.js, Leaflet, OpenStreetMap
Middleware: Rest API
Back-end: Node.js with Express.js
Data: Postgis (Postgresql)
