### ISSUE TITLE
Create new spotType

### ISSUE THREAD

**Issue by tsukasa2** [matsuoharuki/pbl2_group2#83]
Create new spotTypes  
Make sure there is no overlap with other spotTypes

[Points: X] 

[Value: Medium]

[Risk: Low]

**Tasks breakdown**
- [ ] Create new spotTypes(20min)
- [ ] Make sure there is no overlap with other spotTypes(20min)
- [ ] Design a new icon for each spotType(20min)

**Implementation Breakdown**
- [ ] Suggest the required spotType
- [ ] Consider whether there is any overlap in spotType
- [ ] Find the available icons

**Comment by matsuoharuki** [comment]
時間を見つけて討議(4/14)
