### ISSUE TITLE
View others' profiles

### ISSUE THREAD

**Issue by tsukasa2** [matsuoharuki/pbl2_group2#85]
View others' profiles

[Points: X] 

[Value: High]

[Risk: High]

**Tasks breakdown**
- [x] Show others' profiles(2 hours)
- [x] On a spot page,  show the users who have reviewed it(2 hours)
- [ ] When implementing the follow feature, etc.  also add the user display(? hours)

**Implementation Breakdown**
- [x] BACK: Implement the getUserByUserId method
- [x] FRONT: Displays the profile of the user with the specified user ID
- [x] FRONT: Implement a button to display the user's profile
