### ISSUE TITLE
Categorize the data by university

### ISSUE THREAD

**Issue by tsukasa2** [matsuoharuki/pbl2_group2#86]
Re-construct the schema (university name).user  
Add the schema when new university students are added  

Investigate whether it can be operated more efficiently  

[Points: X] 

[Value: High]

[Risk: High]

**Tasks breakdown**
- [ ] Determine the structure of the database(1 hour)
- [ ] create univ database. 
- [ ] create UI to select univ.

**Implementation Breakdown**
- [ ] TBD
