### ISSUE TITLE
Database for images

### ISSUE THREAD

**Issue by tsukasa2** [matsuoharuki/pbl2_group2#87]
Make images available in the database

[Points: X] 

[Value: High]

[Risk: High]

**Tasks breakdown**
- [ ] Encode the image to base 64 (30 min)
- [ ] Save the base 64 in the database (2 hours)
- [ ] Get the base 64 from the database (30 min)
- [ ] Decode the base 64 to image(30 min)

**Implementation Breakdown**
- [ ] Encode is already nearly implemented ?
- [ ] Determine the structure of the database(ID?, column?, Array?)
- [ ] Make function getImageByXXX
- [ ] Find out whether HTML can display the base 64( implement if needed )
