### ISSUE TITLE
Avatar Settings

### ISSUE THREAD

**Issue by tsukasa2** [matsuoharuki/pbl2_group2#88]
ユーザーのプロフィール画像を設定，編集できるようにする
ヘッダーのアイコンにユーザーのプロフィール画像を表示する

[Points: X] 

[Value: Medium]

[Risk: Low]

**Tasks breakdown**
- [ ] View the images got from the backend(30 min)
- [ ] Add a profile picture edit to any menu(1 hour)
- [ ] Implement functions to save, edit, and delete user images in base 64(30 min)

**Implementation Breakdown**
- [ ] Display the images got from the backend
- [ ] Add a profile picture edit to any menu
- [ ] Implement functions to save, edit, and delete user images in base 64
