### ISSUE TITLE
Show reviews in a graph

### ISSUE THREAD

**Issue by tsukasa2** [matsuoharuki/pbl2_group2#89]
Decide the evaluation criteria for each category (need to decide on the category first)
Three to six evaluation criteria (Triangles to hexagons)
Show graphs

[Points: X] 

[Value: High]

[Risk: Low]

**Tasks breakdown**
- [x] Decide the evaluation criteria for each category(30 min)
- [x] Construct a database and implement methods(30 min)
- [x] Add a section for evaluation criteria to the page to post a spot(30 min)
- [x] Show graphs using vue-chart.js (2 hours)

**Implementation Breakdown**
- [x] BACK: getScoreBySpotId
- [x] FRONT: Display the averages for each axis in a graph
