### ISSUE TITLE
Beta version

### ISSUE THREAD

**Issue by Asada0815** [matsuoharuki/pbl2_group2#90]
### front
- [x] submit a review ( Asada, Shimizu )
- [x] update spot detail UI after submitting a review ( Asada, Shimizu )
- [x] page transition from the map page to the review detail page ( Asada, Shimizu )
- [x] make function to get map type ( Takata )
- [x] #97 get spot information reviewed or created by a specific user ( Takata, Nakamura )
- [x] getSpot functionの条件 ( Matsuo, Nakamura )
- [x] #95 if user state is 'logined', spot register function is disabled. ( Yamate )
- [x] #95 edit user by vuex data (Yamate) 
- [x] #92 create logout button on header.  ( Olivier )
- [x] fix a bug of nowLocButton. (Matsuo)
- [x] #115 Profile Picture
- [x] #117 Front end filters 

### back
- [x] #116 Database to store picture
- [x] #117 Add filters for the front end map

**Comment by takata6080** [comment]
- マップTYPEの関数化
- UserIDから「ユーザーがレビューしたスポット情報」、「ユーザーが作ったスポット情報」を取得する関数のテスト・実装

**Comment by matsuoharuki** [comment]
front
- [ ] now location icon(after beta)
- [ ] spot type share(after beta version)
- [x] spot detail dialog(after beta version)
- [ ] setting zoom(after bata version)
- [ ] remember "fix a bug of nowLocButton." (after beta version)
